apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  namespace: pedidos-veloz
  labels:
    app: pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: pagamentos
          image: ghcr.io/dieggo775/pedidos-veloz-pagamentos:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
